import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { getAllTopics } from "@/lib/posts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const topics = getAllTopics();

  return (
    <html lang="en">
      <body className="prose max-w-none">
        <Header topics={topics} />
        {children}
      </body>
    </html>
  );
}